# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish (linux-x64)
      run: dotnet publish -o publish/linux-x64/ -c Release -r linux-x64 --self-contained true -p:PublishTrimmed=true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true
    - name: Publish (win-x64)
      run: dotnet publish -o publish/windows-x64/ -c Release -r win-x64 --self-contained true -p:PublishTrimmed=true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true
    - name: Rename/Move Files
      run: |
        mv publish/linux-x64/WaybackDiffViewer publish/WaybackDiffViewer-linux-x64
        mv publish/windows-x64/WaybackDiffViewer.exe publish/WaybackDiffViewer-windows-x64.exe
    - name: Upload Linux x64
      uses: actions/upload-artifact@v4.3.4
      with:
        name: WaybackDiffViewer-linux-x64
        path: publish/WaybackDiffViewer-linux-x64
    - name: Upload Windows x64
      uses: actions/upload-artifact@v4.3.4
      with:
        name: WaybackDiffViewer-windows-x64.exe
        path: publish/WaybackDiffViewer-windows-x64.exe
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        generate_release_notes: true
        files: |
          publish/WaybackDiffViewer-linux-x64
          publish/WaybackDiffViewer-windows-x64.exe
